import type { GatsbyBrowser } from "gatsby"
// Self-hosted fonts (@fontsource files): latin + cyrillic subsets with
// unicode-range, generated by scripts/build-fonts.mjs.
import "./src/styles/fonts.css"
import "./src/styles/global.css"

// Client-side page changes (EN ⇄ UA) remount the layout: don't replay the
// intro, and start the hero choreography immediately.
export const onPreRouteUpdate: GatsbyBrowser["onPreRouteUpdate"] = ({ location, prevLocation }) => {
  if (prevLocation && prevLocation.pathname !== location.pathname) document.documentElement.classList.add("nointro")
}

