// Generates src/styles/fonts.css from @fontsource: only the weights/styles we
// use, only the latin + cyrillic subsets, woff2 only, *with* unicode-range
// (fontsource's per-subset files omit it, so browsers would fetch every subset).
// Run after changing fonts: `node scripts/build-fonts.mjs`
import { readFileSync, writeFileSync } from "node:fs"

const faces = [
  ["playfair-display", ["400", "500", "400-italic", "500-italic"]],
  ["montserrat", ["300", "400", "500"]],
  ["pinyon-script", ["400"]],
  ["marck-script", ["400"]],
]
const subsets = /-(latin|cyrillic)-\d{3}-(normal|italic) \*\//

let out = "/* Generated by scripts/build-fonts.mjs, do not edit. */\n"
for (const [pkg, files] of faces) {
  for (const f of files) {
    const css = readFileSync(`node_modules/@fontsource/${pkg}/${f}.css`, "utf8")
    for (const block of css.split(/(?=\/\* )/)) {
      if (!subsets.test(block.split("\n")[0])) continue
      out += block
        .replace(/url\(\.\/files\/([^)]+)\.woff2\) format\('woff2'\), url\([^)]+\) format\('woff'\)/, `url(../../node_modules/@fontsource/${pkg}/files/$1.woff2) format('woff2')`)
        .trim() + "\n"
    }
  }
}
writeFileSync("src/styles/fonts.css", out)
console.log(`fonts.css: ${(out.match(/@font-face/g) || []).length} faces`)
